import type { Category, KnowledgeArticle, TicketDetail, TicketSummary, User } from '../app/core/models';
export const base = import.meta.env['VITE_API_BASE_URL'] || 'http://localhost:8081/api/v1';
async function request<T>(path: string, init?: RequestInit): Promise<T> { const r = await fetch(`${base}${path}`, { headers: { 'Content-Type': 'application/json' }, ...init }); if (!r.ok) throw new Error((await r.text()) || `Request failed (${r.status})`); return r.status === 204 ? undefined as T : r.json(); }
export const api = {
 users: () => request<User[]>('/users'), categories: () => request<Category[]>('/categories'), tickets: (q='') => request<TicketSummary[]>(`/tickets${q}`), ticket: (id:string) => request<TicketDetail>(`/tickets/${id}`),
 createTicket: (body: unknown) => request<TicketSummary>('/tickets', {method:'POST',body:JSON.stringify(body)}), updateTicket:(id:string,body:unknown)=>request(`/tickets/${id}`,{method:'PUT',body:JSON.stringify(body)}), deleteTicket:(id:number)=>request(`/tickets/${id}`,{method:'DELETE'}),
 createResponse:(ticketId:string,body:unknown)=>request(`/tickets/${ticketId}/responses`,{method:'POST',body:JSON.stringify(body)}), agentRuns:(ticketId:string)=>request<any[]>(`/tickets/${ticketId}/agent-runs`), agentEvents:(ticketId:string,runId:string)=>request<any[]>(`/tickets/${ticketId}/agent-runs/${runId}/events`), approvals:(ticketId:string,runId:string)=>request<any[]>(`/tickets/${ticketId}/agent-runs/${runId}/approvals`), decideApproval:(ticketId:string,runId:string,approvalId:string,decision:'approve'|'reject',note='')=>request<any>(`/tickets/${ticketId}/agent-runs/${runId}/approvals/${approvalId}/${decision}`,{method:'POST',body:JSON.stringify({note})}),
 knowledge:(q='')=>request<KnowledgeArticle[]>(`/knowledge${q}`), createKnowledge:(body:unknown)=>request('/knowledge',{method:'POST',body:JSON.stringify(body)}), updateKnowledge:(id:number,body:unknown)=>request(`/knowledge/${id}`,{method:'PUT',body:JSON.stringify(body)}), deleteKnowledge:(id:number)=>request(`/knowledge/${id}`,{method:'DELETE'}),
 createUser:(body:unknown)=>request('/users',{method:'POST',body:JSON.stringify(body)}), updateUser:(id:number,body:unknown)=>request(`/users/${id}`,{method:'PUT',body:JSON.stringify(body)}), deleteUser:(id:number)=>request(`/users/${id}`,{method:'DELETE'}), createCategory:(body:unknown)=>request('/categories',{method:'POST',body:JSON.stringify(body)}), updateCategory:(id:number,body:unknown)=>request(`/categories/${id}`,{method:'PUT',body:JSON.stringify(body)}), deleteCategory:(id:number)=>request(`/categories/${id}`,{method:'DELETE'}), analyze:(id:string)=>request(`/tickets/${id}/analyze`,{method:'POST',body:'{}'})
};
