/**
 * set-env.js — run before `ng build` on Vercel to inject the
 * ANGULAR_API_BASE_URL environment variable into environment.prod.ts.
 *
 * Vercel build command:
 *   node scripts/set-env.js && ng build --configuration production
 */
const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

const apiBaseUrl = process.env.ANGULAR_API_BASE_URL || 'http://localhost:8080/api';

const content = `// Auto-generated by scripts/set-env.js — do not edit by hand.
export const environment = {
  production: true,
  apiBaseUrl: '${apiBaseUrl}',
};
`;

fs.writeFileSync(targetPath, content, { encoding: 'utf8' });
console.log(`[set-env] Wrote environment.prod.ts with apiBaseUrl=${apiBaseUrl}`);
